### ISSUE TITLE
Change weisslab to github

### ISSUE THREAD

**Issue by thompson318** [SciKit-Surgery/scikit-surgerytutorial02#22]
Hi Steve,

I've started getting familiar with Python and it is going well. Yesterday I tried going through the software development tutorial but ran into some issues with my account. When I enter the following line into the terminal,
cookiecutter https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/PythonTemplate.git

I am prompted to enter my wesslab.cs.ucl.ac.uk login details which should be my UCL single sign-on details. However, when I enter them, I keep getting this error. 

subprocess.CalledProcessError: Command '['git', 'clone', 'https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/PythonTemplate.git']' returned non-zero exit status 128.

I have tried searching what this error could be due to but have had no luck. Is this perhaps a permission issue or something to do with my account? I will keep searching online for a solution, please let me know if you have an idea of why this is occurring.

Thank you.

Best wishes,
Asta

**Comment by mxochicale** [comment]
Sorted out here https://github.com/SciKit-Surgery/scikit-surgerytutorial02/pull/27
