### ISSUE TITLE
Adds "Goals of Good Software Design" in 04_Planning.rst

### ISSUE THREAD

**Issue by mxochicale** [SciKit-Surgery/scikit-surgerytutorial02#32]
Consider to add a summary of [`Goals of Good Software Design`](https://github.com/lorensen/VTKExamples/blob/master/src/VTKBook/02Chapter2.md#22-goals-of-good-software-design) in [04_Planning.rst](https://github.com/SciKit-Surgery/scikit-surgerytutorial02/blob/master/doc/04_Planning.rst). Goals indicate to be robust, understandable, extendible, modular, maintainable, and reusable.

**Comment by thompson318** [comment]
I agree we should add this.

**Comment by mxochicale** [comment]
In planning, we might also like to add something along the lines of release cycle (schedules for alpha, beta, RC and full bugfix support). See how python version are done: https://peps.python.org/pep-0602/

**Comment by mxochicale** [comment]
Close on behalf of #33
