### ISSUE TITLE
Feedback and comments from the replication of the tutorial02 by Sujon Hekim

### ISSUE THREAD

**Issue by mxochicale** [SciKit-Surgery/scikit-surgerytutorial02#36]
Raising this one because "Authentication failed"

remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/mxochicale/scikit-surgerytutorial02-test.git/'

**Comment by mxochicale** [comment]
A good practice is to connect with GitHub is via Secure Shell Protocol (SSH), which I think is missing in the documentation. So, one can generate SSH keys as suggested [here](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) (or [here](https://github.com/mxochicale/tools/blob/main/github/SSH.md)). User also needs to "[Adds a new SSH key to GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)."

Then do
```
cd sksurgeryspherefitting/
git init
git branch -m main
git add .
git commit -m "Initial commit of my sphere fitter"
git remote add origin git@github.com:mxochicale/sksurgeryspherefitting.git
git push origin master
```


Notes: 
* add vi reference for commands > https://www.redhat.com/sysadmin/introduction-vi-editor
* do we really need pandoc for this tutorial?

**Comment by mxochicale** [comment]
One useful command is also removing already merged branches using:
```
git branch --merged | grep -i -v -E "master" | xargs git branch -d 
```
Source: https://www.w3docs.com/snippets/git/how-to-delete-already-merged-git-branches.html

**Comment by mxochicale** [comment]
Instructions for virtual environment seems to not be clear, so perhaps we can add further instructions.

**Comment by mxochicale** [comment]
Add steps to make more visible this one "Edit the file pylintrc, which is in the tests directory. Near the top of the file is an entry called ignore, add “ui” to the list of things to ignore;"

**Comment by mxochicale** [comment]
Investigate why we get  `__main__.py, __init__.py` that brings other linting errors https://github.com/mxochicale/scikit-surgerytutorial02-test

**Comment by AbuAbdul1ah** [comment]
Error from tox -e lint on Window's computer

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\users\\musa_\\onedrive\\documents\\sksurgeryspherefittingtest2\\.tox\\lint\\lib\\site-packages\\virtualenv-20.23.1.dist-info\\METADATA'

lint: exit 1 (41.91 seconds) C:\Users\musa_\OneDrive\Documents\sksurgeryspherefittingtest2> python -I -m pip install pylint -r requirements-dev.txt pid=11200
  lint: FAIL code 1 (42.09 seconds)
  evaluation failed :( (42.70 seconds)
(scikit-surgeryTUTORIAL02VE)

**Comment by mxochicale** [comment]
update version of requirements for vtk:
`vtk>=9.2.6` > aligning with https://github.com/SciKit-Surgery/scikit-surgerytutorial02/blob/master/requirements.txt

**Comment by mxochicale** [comment]
Select two vtp files and drop them into [vtk_GeometryViewer](https://kitware.github.io/vtk-js/examples/GeometryViewer/index.html)

**Comment by mxochicale** [comment]
Update python version of `For github actions, you will need to amend /.github/workflows/ci.yml using only python version 3.7
`

**Comment by mxochicale** [comment]
Further instructions on how the build is completed and how to commit new messages
* `Test it out. Your documentation on readthedocs should now be automatically updated each time you push a commit to GitHub.`

**Comment by mxochicale** [comment]
Not clear "readthedocs or WEISSLab " > in "Wait until the continuous integration tests have finished on WEISSLab. You should now be able to visit your code on readthedocs or WEISSLab and see three green boxes, showing that your code is tested (with 100% coverage) and that the docs are building. To anyone considering using your code this would be very encouraging."
